vm_name = 'ansible-course-03'
rsync_excl = ['.git/', '.vagrant/']

Vagrant.configure('2') do |config|
  unless ENV['http_proxy'].nil?
    config.proxy.enabled  = true
    # set values from environmental variables
    config.proxy.http     = ENV['http_proxy']
    config.proxy.https    = ENV['http_proxy']
    config.proxy.no_proxy = ENV['no_proxy']
  end

  config.vm.synced_folder './', '/vagrant', type: 'rsync', rsync__exclude: rsync_excl
  config.vm.box = 'bento/centos-7.4'
  config.vm.provision 'ansible_local' do |ansible|
    ansible.playbook = '/vagrant/provision_me.yml'
    ansible.verbose = 'vv'
  end

  config.vm.provider 'hyperv' do |h|
    h.vm_integration_services = {
      guest_service_interface: true,
      time_synchronization: true
    }
    h.memory  = 512
    h.vmname  = vm_name
  end
end
