vm_name = 'Tads system'
rsync_ignore = ['out_of_context/']

Vagrant.configure('2') do |config|
  unless ENV['http_proxy'].nil?
    config.proxy.enabled  = true
    config.proxy.http     = ENV['http_proxy']
    config.proxy.https    = ENV['http_proxy']
    config.proxy.no_proxy = ENV['no_proxy']
  end


 config.vm.define "master" do |master|
    master.vm.hostname = 'master'
    master.vm.box = "ubuntu/precise64"

    master.vm.network :private_network, ip: "192.168.56.101"
    master.vm.network "forwarded_port", guest: 80, host: 2141

    master.vm.provider :virtualbox do |vb|
      vb.memory = 1024
    end
  end


config.vm.define "development" do |dev|
    dev.vm.hostname = 'dev'
    dev.vm.box = "ubuntu/precise64"

    dev.vm.network :private_network, ip: "192.168.56.102"
    dev.vm.network "forwarded_port", guest: 80, host: 2142

    dev.vm.provider :virtualbox do |vb|
      vb.memory = 1024
    end
  end


config.vm.define "production" do |prod|
    prod.vm.hostname = 'dev'
    prod.vm.box = "ubuntu/precise64"

    prod.vm.network :private_network, ip: "192.168.56.103"
    prod.vm.network "forwarded_port", guest: 80, host: 2143

    prod.vm.provider :virtualbox do |vb|
      vb.memory = 1024
    end
  end

end
