Vagrant.configure(2) do |config|
  config.vm.define "vm1" do |subconfig|
   config.vm.box = "centos/8"
   config.vm.hostname = "vm1"
   config.vm.provision :shell, path: "bootstrap.sh"
   config.vm.network :private_network, ip: "192.168.50.11"
   config.vm.network "forwarded_port", guest: 22, host: 2222
   config.vm.provider "virtualbox" do |v|
    v.cpus = "1"
    v.memory = 2048
   end
  end

  config.ssh.insert_key = false
    config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
end
